In [1]:
import os
import numpy as np

In [2]:
#validation_data_dir = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation/Cat'
validation_data_dir = 'I:\\1_ssd_m.2\\PetImages\\validation\\Cat'


######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtension =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir):                                        
    FilesAndExtension.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtension)

[('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('103', '.jpg'), ('104', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('121', '.jpg'), ('122', '.jpg'), ('123', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.

In [3]:
from keras.models import load_model

#path_best_model = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/0.9780__146-0.17-0.9945_CatsVRDogs_4000_inceptionV3_softmaxP98.h5'

#path_best_model = 'F:\\petsTF20model_weights\\CATSvsDOGS_4000_2000_inceptionV3_softmax_model.save98_TF2.1win.h5'

#model = load_model(path_best_model)

#model.load_weights('F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5')




path_best_model = 'F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5'

model = load_model(path_best_model)

Using TensorFlow backend.


In [4]:
import cv2
import shutil

from matplotlib import pyplot

from keras.preprocessing import image
from keras.applications.inception_v3 import preprocess_input, decode_predictions
#result = model.evaluate(x=valida_x, y=valida_y) 

#next_validation_dir = '/media/ssd/Windows7_1/TB_DB_448_predict_sortANDcopy_classify_loop/2/validation/tb'
#next_validation_dir = 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\cats'

positiv=0
negativ=0

position00=0
position01=0

cats_position00 = 0 
cats_position01 = 0

for x in range(len(FilesAndExtension)):
    print(x)

    #print(FilesAndExtension[0][0] + FilesAndExtension[0][1])
    img_path = validation_data_dir + '\\' + FilesAndExtension[x][0] + FilesAndExtension[x][1]
    
    img = image.load_img(img_path, target_size=(150, 150))
    
    
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1 = image.img_to_array(img)
      
    #normalization of the image to 0 ... 1
    x1_norm = x1 / 255.0
    
    
    # of size (1, 224, 224, 3)
    x2 = np.expand_dims(x1_norm, axis=0)
    
     
    #x3 = preprocess_input(x2) //no method preprocess_input() and normalization, it works
    
    #############################################################################
    # load and pre-process data
    #def preprocess_input(x):
    #    return x.astype('float32').reshape((-1,) + input_shape) / 255
    #
    #https://keras.io/examples/mnist_net2net/
    #keras/examples/mnist_net2net.py 
    #https://github.com/keras-team/keras/blob/fb8fef251c817ebc9509b90e613cb5758f42803b/examples/mnist_net2net.py#L84
    ###############################################################################
    
    result = model.predict(x2)
    #result = model.predict(x3)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
     
    

    if Labels_result == 0:
        
        positiv=positiv + 1
        
    if Labels_result == 1:
        
        negativ = negativ + 1
        
        
        
    if result[0,0] >= 0.5:
        
        position00 = position00 + 1
        
    if result[0,1]  >= 0.5:
        
        position01 = position01 + 1

        
        
        
    if result[0,0] > result[0,1]: 
        
        cats_position00 = cats_position00 + 1
        
        
    if result[0,1]  > result[0,0]:
        
        cats_position01 = cats_position01 + 1

        
        
        
        
        
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)



print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)





#class_indices
#{'Cat': 0, 'Dog': 1}

0
[0]
[[1. 0.]]
1.0
0.0
 
 
1
[0]
[[1. 0.]]
1.0
0.0
 
 
2
[0]
[[1.0000000e+00 6.4940503e-10]]
1.0
6.4940503e-10
 
 
3
[0]
[[1. 0.]]
1.0
0.0
 
 
4
[0]
[[0.98909074 0.01090926]]
0.98909074
0.010909256
 
 
5
[0]
[[1. 0.]]
1.0
0.0
 
 
6
[0]
[[1. 0.]]
1.0
0.0
 
 
7
[0]
[[1. 0.]]
1.0
0.0
 
 
8
[0]
[[1. 0.]]
1.0
0.0
 
 
9
[0]
[[9.9999964e-01 4.0588736e-07]]
0.99999964
4.0588736e-07
 
 
10
[0]
[[1. 0.]]
1.0
0.0
 
 
11
[0]
[[1.0000000e+00 2.8837704e-20]]
1.0
2.8837704e-20
 
 
12
[0]
[[1. 0.]]
1.0
0.0
 
 
13
[0]
[[0.6550032 0.3449968]]
0.6550032
0.3449968
 
 
14
[0]
[[1.000000e+00 9.443866e-22]]
1.0
9.443866e-22
 
 
15
[0]
[[1.000000e+00 7.478791e-27]]
1.0
7.478791e-27
 
 
16
[0]
[[1. 0.]]
1.0
0.0
 
 
17
[0]
[[1. 0.]]
1.0
0.0
 
 
18
[0]
[[1. 0.]]
1.0
0.0
 
 
19
[0]
[[1. 0.]]
1.0
0.0
 
 
20
[0]
[[1. 0.]]
1.0
0.0
 
 
21
[0]
[[1. 0.]]
1.0
0.0
 
 
22
[0]
[[1. 0.]]
1.0
0.0
 
 
23
[0]
[[1. 0.]]
1.0
0.0
 
 
24
[0]
[[1. 0.]]
1.0
0.0
 
 
25
[0]
[[1. 0.]]
1.0
0.0
 
 
26
[0]
[[1. 0.]]
1.0
0.0
 
 
27
[0]
[[

[0]
[[1.0000000e+00 1.2878103e-18]]
1.0
1.2878103e-18
 
 
193
[0]
[[1. 0.]]
1.0
0.0
 
 
194
[0]
[[1. 0.]]
1.0
0.0
 
 
195
[0]
[[1. 0.]]
1.0
0.0
 
 
196
[0]
[[1.000000e+00 1.570757e-29]]
1.0
1.570757e-29
 
 
197
[0]
[[1. 0.]]
1.0
0.0
 
 
198
[0]
[[1.000000e+00 8.170609e-31]]
1.0
8.170609e-31
 
 
199
[0]
[[9.9999988e-01 1.2618229e-07]]
0.9999999
1.2618229e-07
 
 
200
[0]
[[1. 0.]]
1.0
0.0
 
 
201
[0]
[[1. 0.]]
1.0
0.0
 
 
202
[0]
[[1. 0.]]
1.0
0.0
 
 
203
[0]
[[1. 0.]]
1.0
0.0
 
 
204
[0]
[[1. 0.]]
1.0
0.0
 
 
205
[0]
[[1.000000e+00 7.171154e-29]]
1.0
7.171154e-29
 
 
206
[0]
[[1.00000e+00 3.56668e-11]]
1.0
3.56668e-11
 
 
207
[0]
[[1. 0.]]
1.0
0.0
 
 
208
[0]
[[1. 0.]]
1.0
0.0
 
 
209
[0]
[[1. 0.]]
1.0
0.0
 
 
210
[0]
[[1.000000e+00 8.942687e-11]]
1.0
8.942687e-11
 
 
211
[0]
[[9.9999821e-01 1.7366816e-06]]
0.9999982
1.7366816e-06
 
 
212
[0]
[[1. 0.]]
1.0
0.0
 
 
213
[0]
[[1.0000000e+00 1.3289349e-08]]
1.0
1.3289349e-08
 
 
214
[0]
[[1. 0.]]
1.0
0.0
 
 
215
[0]
[[1.000000e+00 2.311175e

[0]
[[1. 0.]]
1.0
0.0
 
 
391
[0]
[[1. 0.]]
1.0
0.0
 
 
392
[0]
[[1. 0.]]
1.0
0.0
 
 
393
[1]
[[0.13006857 0.86993146]]
0.13006857
0.86993146
 
 
394
[0]
[[1. 0.]]
1.0
0.0
 
 
395
[0]
[[1. 0.]]
1.0
0.0
 
 
396
[0]
[[1.0000000e+00 2.1789712e-18]]
1.0
2.1789712e-18
 
 
397
[0]
[[1. 0.]]
1.0
0.0
 
 
398
[0]
[[1. 0.]]
1.0
0.0
 
 
399
[0]
[[1. 0.]]
1.0
0.0
 
 
400
[0]
[[1.000000e+00 7.339187e-24]]
1.0
7.339187e-24
 
 
401
[0]
[[1.000000e+00 6.725036e-09]]
1.0
6.725036e-09
 
 
402
[0]
[[9.9999976e-01 2.1734581e-07]]
0.99999976
2.1734581e-07
 
 
403
[0]
[[1. 0.]]
1.0
0.0
 
 
404
[0]
[[1. 0.]]
1.0
0.0
 
 
405
[0]
[[1. 0.]]
1.0
0.0
 
 
406
[0]
[[1.0000000e+00 4.5287416e-16]]
1.0
4.5287416e-16
 
 
407
[0]
[[1.0000000e+00 2.0771901e-19]]
1.0
2.0771901e-19
 
 
408
[0]
[[1.0000000e+00 1.6508983e-08]]
1.0
1.6508983e-08
 
 
409
[0]
[[1.000000e+00 5.868983e-20]]
1.0
5.868983e-20
 
 
410
[0]
[[1. 0.]]
1.0
0.0
 
 
411
[0]
[[1. 0.]]
1.0
0.0
 
 
412
[0]
[[1. 0.]]
1.0
0.0
 
 
413
[0]
[[1. 0.]]
1.0
0.0
 
 


[0]
[[1. 0.]]
1.0
0.0
 
 
579
[0]
[[1. 0.]]
1.0
0.0
 
 
580
[0]
[[9.9998140e-01 1.8569535e-05]]
0.9999814
1.8569535e-05
 
 
581
[0]
[[1. 0.]]
1.0
0.0
 
 
582
[0]
[[1.000000e+00 8.098222e-37]]
1.0
8.098222e-37
 
 
583
[0]
[[1. 0.]]
1.0
0.0
 
 
584
[0]
[[1. 0.]]
1.0
0.0
 
 
585
[0]
[[1. 0.]]
1.0
0.0
 
 
586
[0]
[[1.0000000e+00 1.3841301e-14]]
1.0
1.3841301e-14
 
 
587
[0]
[[1.00000e+00 6.41052e-23]]
1.0
6.41052e-23
 
 
588
[0]
[[1. 0.]]
1.0
0.0
 
 
589
[0]
[[1. 0.]]
1.0
0.0
 
 
590
[0]
[[1. 0.]]
1.0
0.0
 
 
591
[0]
[[1. 0.]]
1.0
0.0
 
 
592
[0]
[[1. 0.]]
1.0
0.0
 
 
593
[0]
[[1. 0.]]
1.0
0.0
 
 
594
[0]
[[1.000000e+00 5.845703e-19]]
1.0
5.845703e-19
 
 
595
[0]
[[1. 0.]]
1.0
0.0
 
 
596
[0]
[[1. 0.]]
1.0
0.0
 
 
597
[0]
[[1. 0.]]
1.0
0.0
 
 
598
[0]
[[1. 0.]]
1.0
0.0
 
 
599
[0]
[[1. 0.]]
1.0
0.0
 
 
600
[0]
[[1.0000000e+00 2.0420898e-23]]
1.0
2.0420898e-23
 
 
601
[0]
[[1. 0.]]
1.0
0.0
 
 
602
[0]
[[1. 0.]]
1.0
0.0
 
 
603
[0]
[[1. 0.]]
1.0
0.0
 
 
604
[0]
[[1.0000000e+00 1.4078574e-20]

[0]
[[1. 0.]]
1.0
0.0
 
 
767
[0]
[[9.9993324e-01 6.6797373e-05]]
0.99993324
6.679737e-05
 
 
768
[0]
[[1. 0.]]
1.0
0.0
 
 
769
[0]
[[1.000000e+00 1.863001e-15]]
1.0
1.863001e-15
 
 
770
[0]
[[1.00000000e+00 1.08150254e-20]]
1.0
1.08150254e-20
 
 
771
[0]
[[1.000000e+00 1.315961e-14]]
1.0
1.315961e-14
 
 
772
[0]
[[1. 0.]]
1.0
0.0
 
 
773
[0]
[[1.0000000e+00 6.7260533e-34]]
1.0
6.7260533e-34
 
 
774
[0]
[[1. 0.]]
1.0
0.0
 
 
775
[0]
[[1. 0.]]
1.0
0.0
 
 
776
[0]
[[9.9994576e-01 5.4192380e-05]]
0.99994576
5.419238e-05
 
 
777
[0]
[[1. 0.]]
1.0
0.0
 
 
778
[0]
[[1.0000000e+00 1.7423592e-31]]
1.0
1.7423592e-31
 
 
779
[0]
[[1. 0.]]
1.0
0.0
 
 
780
[0]
[[0.9834741  0.01652594]]
0.9834741
0.016525945
 
 
781
[0]
[[1. 0.]]
1.0
0.0
 
 
782
[0]
[[1.0000000e+00 1.7319235e-11]]
1.0
1.7319235e-11
 
 
783
[0]
[[1. 0.]]
1.0
0.0
 
 
784
[0]
[[1. 0.]]
1.0
0.0
 
 
785
[0]
[[1. 0.]]
1.0
0.0
 
 
786
[0]
[[1.0000000e+00 7.7913533e-19]]
1.0
7.7913533e-19
 
 
787
[0]
[[1. 0.]]
1.0
0.0
 
 
788
[0]
[[1. 0.]]

[0]
[[1. 0.]]
1.0
0.0
 
 
958
[0]
[[1. 0.]]
1.0
0.0
 
 
959
[0]
[[1. 0.]]
1.0
0.0
 
 
960
[0]
[[1. 0.]]
1.0
0.0
 
 
961
[0]
[[1. 0.]]
1.0
0.0
 
 
962
[0]
[[1. 0.]]
1.0
0.0
 
 
963
[0]
[[1. 0.]]
1.0
0.0
 
 
964
[0]
[[9.9991655e-01 8.3416926e-05]]
0.99991655
8.3416926e-05
 
 
965
[0]
[[1. 0.]]
1.0
0.0
 
 
966
[0]
[[1.0000000e+00 6.2540487e-15]]
1.0
6.2540487e-15
 
 
967
[0]
[[9.9999738e-01 2.6472117e-06]]
0.9999974
2.6472117e-06
 
 
968
[0]
[[1.000000e+00 9.947485e-33]]
1.0
9.947485e-33
 
 
969
[0]
[[1. 0.]]
1.0
0.0
 
 
970
[0]
[[1.000000e+00 1.554986e-09]]
1.0
1.554986e-09
 
 
971
[1]
[[8.3573197e-04 9.9916434e-01]]
0.000835732
0.99916434
 
 
972
[0]
[[1.0000000e+00 9.5413195e-35]]
1.0
9.5413195e-35
 
 
973
[0]
[[0.9932374  0.00676259]]
0.9932374
0.006762589
 
 
974
[0]
[[1. 0.]]
1.0
0.0
 
 
975
[0]
[[1. 0.]]
1.0
0.0
 
 
976
[0]
[[1.000000e+00 4.332606e-19]]
1.0
4.332606e-19
 
 
977
[0]
[[1. 0.]]
1.0
0.0
 
 
978
[0]
[[1.000000e+00 7.672382e-17]]
1.0
7.672382e-17
 
 
979
[0]
[[9.9999976e

In [5]:
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)
print("positiv in percent: ", format((positiv / (positiv + negativ) * 100), '.2f'),'%')
print("negativ in percent: ", format((negativ / (positiv + negativ) * 100), '.2f'),'%')


print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)



#class_indices
#{'Cat': 0, 'Dog': 1}

 
 
positiv:  981
negativ:  19
positiv in percent:  98.10 %
negativ in percent:  1.90 %
 
 
result[0,0]:  981
result[0,1]:  19
 
 
result[0,0] > result[0,1]:  981
result[0,1]  > result[0,0]:  19


In [6]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

batch_size_Tatal_sample_size = 2000 

base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate(x=valida_x, y=valida_y)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 8s 4ms/step
loss 0.35562050810852963
acc 0.9775000214576721
acc: 97.75%


In [7]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

validation_steps = 2000   # 0 till 2000

batch_size_Tatal_sample_size = 20 

base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


#valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate_generator(validation_generator, steps=validation_steps, verbose=1)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 120s 60ms/step
loss 1.2020811482216232e-05
acc 0.9775000214576721
acc: 97.75%


In [8]:
validation_data_dir_normal = 'I:\\1_ssd_m.2\\PetImages\\validation\\Dog'



######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtensionNormal =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir_normal):                                        
    FilesAndExtensionNormal.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtensionNormal)

[('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('103', '.jpg'), ('104', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('121', '.jpg'), ('122', '.jpg'), ('123', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.

In [9]:
#next_validation_dir_dog= '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation_wrong_classicfide/dogs'
next_validation_dir_dog= 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\dogs'

dogs_position00 = 0 
dogs_position01 = 0



for x in range(len(FilesAndExtensionNormal)):
    print(x)

    img_path = validation_data_dir_normal + '\\' + FilesAndExtensionNormal[x][0] + FilesAndExtensionNormal[x][1]
    
    img_d = image.load_img(img_path, target_size=(150, 150))
    
    
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1_d = image.img_to_array(img_d)
    
        
    #normalization of the image to 0 ... 1
    x1_d_0_1 = x1_d / 255.0
    

    # We add a dimension to transform our array into a "batch"
    # of size (1, 224, 224, 3)
    x2_d = np.expand_dims(x1_d_0_1, axis=0)
    
    # Finally we preprocess the batch
    # (this does channel-wise color normalization)
    #x3_d = preprocess_input(x2_d)

    result = model.predict(x2_d)
    #result = model.predict(x3_d)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
    

    if result[0,0] > result[0,1]: 
        
        dogs_position00  = dogs_position00  + 1
        
    if result[0,1]  > result[0,0]:
        
        dogs_position01  = dogs_position01  + 1





print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

#class_indices
#{'Cat': 0, 'Dog': 1}  

0
[1]
[[0. 1.]]
0.0
1.0
 
 
1
[1]
[[0.00101754 0.9989825 ]]
0.0010175365
0.9989825
 
 
2
[1]
[[4.2416596e-05 9.9995756e-01]]
4.2416596e-05
0.99995756
 
 
3
[1]
[[1.9119466e-13 1.0000000e+00]]
1.9119466e-13
1.0
 
 
4
[1]
[[0. 1.]]
0.0
1.0
 
 
5
[1]
[[2.242656e-19 1.000000e+00]]
2.242656e-19
1.0
 
 
6
[1]
[[0. 1.]]
0.0
1.0
 
 
7
[1]
[[7.6851456e-34 1.0000000e+00]]
7.6851456e-34
1.0
 
 
8
[1]
[[1.2094331e-29 1.0000000e+00]]
1.2094331e-29
1.0
 
 
9
[1]
[[0. 1.]]
0.0
1.0
 
 
10
[1]
[[8.844509e-25 1.000000e+00]]
8.844509e-25
1.0
 
 
11
[1]
[[0. 1.]]
0.0
1.0
 
 
12
[1]
[[0. 1.]]
0.0
1.0
 
 
13
[1]
[[0. 1.]]
0.0
1.0
 
 
14
[1]
[[5.161548e-35 1.000000e+00]]
5.161548e-35
1.0
 
 
15
[1]
[[1.8986981e-19 1.0000000e+00]]
1.8986981e-19
1.0
 
 
16
[1]
[[0. 1.]]
0.0
1.0
 
 
17
[1]
[[8.371136e-31 1.000000e+00]]
8.371136e-31
1.0
 
 
18
[1]
[[8.390892e-09 1.000000e+00]]
8.390892e-09
1.0
 
 
19
[1]
[[8.640094e-31 1.000000e+00]]
8.640094e-31
1.0
 
 
20
[1]
[[0. 1.]]
0.0
1.0
 
 
21
[1]
[[0. 1.]]
0.0
1.0
 
 


[1]
[[0. 1.]]
0.0
1.0
 
 
184
[1]
[[0. 1.]]
0.0
1.0
 
 
185
[1]
[[0. 1.]]
0.0
1.0
 
 
186
[1]
[[4.8857385e-12 1.0000000e+00]]
4.8857385e-12
1.0
 
 
187
[1]
[[0. 1.]]
0.0
1.0
 
 
188
[1]
[[6.8374896e-11 1.0000000e+00]]
6.8374896e-11
1.0
 
 
189
[1]
[[0. 1.]]
0.0
1.0
 
 
190
[1]
[[0. 1.]]
0.0
1.0
 
 
191
[1]
[[1.5485967e-19 1.0000000e+00]]
1.5485967e-19
1.0
 
 
192
[1]
[[1.576347e-12 1.000000e+00]]
1.576347e-12
1.0
 
 
193
[1]
[[0. 1.]]
0.0
1.0
 
 
194
[1]
[[0. 1.]]
0.0
1.0
 
 
195
[1]
[[0. 1.]]
0.0
1.0
 
 
196
[1]
[[2.3244134e-07 9.9999976e-01]]
2.3244134e-07
0.99999976
 
 
197
[1]
[[1.5433029e-09 1.0000000e+00]]
1.5433029e-09
1.0
 
 
198
[1]
[[1.158307e-26 1.000000e+00]]
1.158307e-26
1.0
 
 
199
[1]
[[0. 1.]]
0.0
1.0
 
 
200
[1]
[[0. 1.]]
0.0
1.0
 
 
201
[1]
[[7.2429015e-05 9.9992752e-01]]
7.2429015e-05
0.9999275
 
 
202
[1]
[[4.5029397e-37 1.0000000e+00]]
4.5029397e-37
1.0
 
 
203
[1]
[[1.1548328e-22 1.0000000e+00]]
1.1548328e-22
1.0
 
 
204
[1]
[[1.4092429e-36 1.0000000e+00]]
1.40924

[1]
[[0. 1.]]
0.0
1.0
 
 
370
[1]
[[5.361828e-32 1.000000e+00]]
5.361828e-32
1.0
 
 
371
[1]
[[5.6597997e-27 1.0000000e+00]]
5.6597997e-27
1.0
 
 
372
[1]
[[0. 1.]]
0.0
1.0
 
 
373
[0]
[[9.9984491e-01 1.5501207e-04]]
0.9998449
0.00015501207
 
 
374
[1]
[[0. 1.]]
0.0
1.0
 
 
375
[1]
[[0. 1.]]
0.0
1.0
 
 
376
[1]
[[0. 1.]]
0.0
1.0
 
 
377
[1]
[[2.1978074e-07 9.9999976e-01]]
2.1978074e-07
0.99999976
 
 
378
[1]
[[1.9198426e-25 1.0000000e+00]]
1.9198426e-25
1.0
 
 
379
[1]
[[1.2171776e-12 1.0000000e+00]]
1.2171776e-12
1.0
 
 
380
[1]
[[0. 1.]]
0.0
1.0
 
 
381
[1]
[[1.602186e-11 1.000000e+00]]
1.602186e-11
1.0
 
 
382
[1]
[[0. 1.]]
0.0
1.0
 
 
383
[1]
[[4.956466e-22 1.000000e+00]]
4.956466e-22
1.0
 
 
384
[1]
[[0. 1.]]
0.0
1.0
 
 
385
[1]
[[0. 1.]]
0.0
1.0
 
 
386
[1]
[[6.910035e-32 1.000000e+00]]
6.910035e-32
1.0
 
 
387
[1]
[[8.7671040e-05 9.9991226e-01]]
8.767104e-05
0.99991226
 
 
388
[1]
[[0. 1.]]
0.0
1.0
 
 
389
[1]
[[0. 1.]]
0.0
1.0
 
 
390
[1]
[[1.9942828e-23 1.0000000e+00]]
1.99428

[1]
[[0.02021906 0.9797809 ]]
0.020219056
0.9797809
 
 
544
[1]
[[6.802897e-06 9.999932e-01]]
6.802897e-06
0.9999932
 
 
545
[1]
[[0. 1.]]
0.0
1.0
 
 
546
[1]
[[3.474631e-09 1.000000e+00]]
3.474631e-09
1.0
 
 
547
[1]
[[0. 1.]]
0.0
1.0
 
 
548
[1]
[[0. 1.]]
0.0
1.0
 
 
549
[1]
[[5.727508e-09 1.000000e+00]]
5.727508e-09
1.0
 
 
550
[1]
[[3.6953628e-16 1.0000000e+00]]
3.6953628e-16
1.0
 
 
551
[1]
[[3.8178535e-28 1.0000000e+00]]
3.8178535e-28
1.0
 
 
552
[1]
[[0. 1.]]
0.0
1.0
 
 
553
[1]
[[5.045715e-27 1.000000e+00]]
5.045715e-27
1.0
 
 
554
[1]
[[8.556064e-31 1.000000e+00]]
8.556064e-31
1.0
 
 
555
[1]
[[0.00178657 0.9982134 ]]
0.001786572
0.9982134
 
 
556
[1]
[[3.7248719e-16 1.0000000e+00]]
3.7248719e-16
1.0
 
 
557
[0]
[[1.000000e+00 8.009751e-19]]
1.0
8.009751e-19
 
 
558
[1]
[[0. 1.]]
0.0
1.0
 
 
559
[1]
[[0. 1.]]
0.0
1.0
 
 
560
[1]
[[7.731694e-19 1.000000e+00]]
7.731694e-19
1.0
 
 
561
[1]
[[4.7547753e-25 1.0000000e+00]]
4.7547753e-25
1.0
 
 
562
[1]
[[0. 1.]]
0.0
1.0
 
 
563
[1]

[1]
[[0. 1.]]
0.0
1.0
 
 
717
[1]
[[0. 1.]]
0.0
1.0
 
 
718
[1]
[[0. 1.]]
0.0
1.0
 
 
719
[1]
[[1.2002983e-25 1.0000000e+00]]
1.2002983e-25
1.0
 
 
720
[1]
[[0. 1.]]
0.0
1.0
 
 
721
[1]
[[1.2333165e-27 1.0000000e+00]]
1.2333165e-27
1.0
 
 
722
[1]
[[1.4254975e-26 1.0000000e+00]]
1.4254975e-26
1.0
 
 
723
[1]
[[5.3864755e-30 1.0000000e+00]]
5.3864755e-30
1.0
 
 
724
[1]
[[0. 1.]]
0.0
1.0
 
 
725
[1]
[[0. 1.]]
0.0
1.0
 
 
726
[1]
[[0. 1.]]
0.0
1.0
 
 
727
[1]
[[0. 1.]]
0.0
1.0
 
 
728
[1]
[[0. 1.]]
0.0
1.0
 
 
729
[1]
[[3.0593064e-35 1.0000000e+00]]
3.0593064e-35
1.0
 
 
730
[1]
[[1.3814966e-12 1.0000000e+00]]
1.3814966e-12
1.0
 
 
731
[1]
[[2.1334838e-28 1.0000000e+00]]
2.1334838e-28
1.0
 
 
732
[1]
[[2.669633e-23 1.000000e+00]]
2.669633e-23
1.0
 
 
733
[1]
[[0. 1.]]
0.0
1.0
 
 
734
[1]
[[4.5903804e-32 1.0000000e+00]]
4.5903804e-32
1.0
 
 
735
[1]
[[8.7008686e-35 1.0000000e+00]]
8.7008686e-35
1.0
 
 
736
[1]
[[0. 1.]]
0.0
1.0
 
 
737
[1]
[[4.330146e-33 1.000000e+00]]
4.330146e-33
1.0
 


[1]
[[0. 1.]]
0.0
1.0
 
 
897
[1]
[[0. 1.]]
0.0
1.0
 
 
898
[1]
[[0. 1.]]
0.0
1.0
 
 
899
[1]
[[2.7320997e-36 1.0000000e+00]]
2.7320997e-36
1.0
 
 
900
[1]
[[0. 1.]]
0.0
1.0
 
 
901
[1]
[[0. 1.]]
0.0
1.0
 
 
902
[1]
[[0. 1.]]
0.0
1.0
 
 
903
[1]
[[1.4909349e-21 1.0000000e+00]]
1.4909349e-21
1.0
 
 
904
[1]
[[1.0081658e-23 1.0000000e+00]]
1.0081658e-23
1.0
 
 
905
[1]
[[7.348007e-07 9.999993e-01]]
7.348007e-07
0.9999993
 
 
906
[1]
[[0. 1.]]
0.0
1.0
 
 
907
[1]
[[0.00192171 0.9980782 ]]
0.0019217106
0.9980782
 
 
908
[1]
[[1.2150767e-07 9.9999988e-01]]
1.2150767e-07
0.9999999
 
 
909
[1]
[[0. 1.]]
0.0
1.0
 
 
910
[1]
[[0. 1.]]
0.0
1.0
 
 
911
[1]
[[0. 1.]]
0.0
1.0
 
 
912
[1]
[[7.7321120e-06 9.9999225e-01]]
7.732112e-06
0.99999225
 
 
913
[1]
[[1.0396016e-07 9.9999988e-01]]
1.0396016e-07
0.9999999
 
 
914
[1]
[[3.949406e-16 1.000000e+00]]
3.949406e-16
1.0
 
 
915
[1]
[[0. 1.]]
0.0
1.0
 
 
916
[1]
[[0. 1.]]
0.0
1.0
 
 
917
[1]
[[0. 1.]]
0.0
1.0
 
 
918
[1]
[[0.00802179 0.99197817]]
0.008

In [10]:
print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

print(" ")
print(" ") 

print("positiv in percent: ", format((dogs_position00  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')
print("negativ in percent: ", format((dogs_position01  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')



result[0,0] > result[0,1]:  26
result[0,1]  > result[0,0]:  974
 
 
positiv in percent:  2.60 %
negativ in percent:  97.40 %
