In [1]:
import os
import numpy as np

In [2]:
validation_data_dir = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation/Cat'
#validation_data_dir = 'I:\\1_ssd_m.2\\PetImages\\validation\\Cat'


######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtension =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir):                                        
    FilesAndExtension.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtension)

[('471', '.jpg'), ('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('103', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('121', '.jpg'), ('122', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.jpg'), ('138', '.

In [3]:
from keras.models import load_model

path_best_model = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/0.9780__146-0.17-0.9945_CatsVRDogs_4000_inceptionV3_softmaxP98.h5'

#path_best_model = 'F:\\petsTF20model_weights\\CATSvsDOGS_4000_2000_inceptionV3_softmax_model.save98_TF2.1win.h5'

#model = load_model(path_best_model)

#model.load_weights('F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5')




### path_best_model = 'F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5'

model = load_model(path_best_model)

Using TensorFlow backend.


In [4]:
import cv2
import shutil

from matplotlib import pyplot

from keras.preprocessing import image
from keras.applications.inception_v3 import preprocess_input, decode_predictions
#result = model.evaluate(x=valida_x, y=valida_y) 

#next_validation_dir = '/media/ssd/Windows7_1/TB_DB_448_predict_sortANDcopy_classify_loop/2/validation/tb'
#next_validation_dir = 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\cats'

positiv=0
negativ=0

position00=0
position01=0

cats_position00 = 0 
cats_position01 = 0

for x in range(len(FilesAndExtension)):
    print(x)

    #print(FilesAndExtension[0][0] + FilesAndExtension[0][1])
    img_path = validation_data_dir + '/' + FilesAndExtension[x][0] + FilesAndExtension[x][1]
    ##img_path = validation_data_dir + '\\' + FilesAndExtension[x][0] + FilesAndExtension[x][1]
    
    img = image.load_img(img_path, target_size=(150, 150))
    
    
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1 = image.img_to_array(img)
      
    #normalization of the image to 0 ... 1
    x1_norm = x1 / 255.0
    
    
    # of size (1, 224, 224, 3)
    x2 = np.expand_dims(x1_norm, axis=0)
    
     
    #x3 = preprocess_input(x2) //no methode preprocess_input() it works
    
     
    
    result = model.predict(x2)
    #result = model.predict(x3)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
     
    

    if Labels_result == 0:
        
        positiv=positiv + 1
        
    if Labels_result == 1:
        
        negativ = negativ + 1
        
        
        
    if result[0,0] >= 0.5:
        
        position00 = position00 + 1
        
    if result[0,1]  >= 0.5:
        
        position01 = position01 + 1

        
        
        
    if result[0,0] > result[0,1]: 
        
        cats_position00 = cats_position00 + 1
        
        
    if result[0,1]  > result[0,0]:
        
        cats_position01 = cats_position01 + 1

        
        
        
        
        
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)



print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)





#class_indices
#{'Dog': 1, 'Cat': 0}

0
[0]
[[1. 0.]]
1.0
0.0
 
 
1
[0]
[[1. 0.]]
1.0
0.0
 
 
2
[0]
[[1. 0.]]
1.0
0.0
 
 
3
[0]
[[1.0000000e+00 3.3406512e-14]]
1.0
3.3406512e-14
 
 
4
[0]
[[1. 0.]]
1.0
0.0
 
 
5
[0]
[[9.9987245e-01 1.2756952e-04]]
0.99987245
0.00012756952
 
 
6
[0]
[[1. 0.]]
1.0
0.0
 
 
7
[0]
[[1. 0.]]
1.0
0.0
 
 
8
[0]
[[1. 0.]]
1.0
0.0
 
 
9
[0]
[[1.0000000e+00 1.9992413e-38]]
1.0
1.9992413e-38
 
 
10
[0]
[[9.99986649e-01 1.33866515e-05]]
0.99998665
1.33866515e-05
 
 
11
[0]
[[1. 0.]]
1.0
0.0
 
 
12
[0]
[[1. 0.]]
1.0
0.0
 
 
13
[0]
[[1. 0.]]
1.0
0.0
 
 
14
[0]
[[0.8386847  0.16131534]]
0.8386847
0.16131534
 
 
15
[0]
[[1.0000000e+00 2.5937634e-11]]
1.0
2.5937634e-11
 
 
16
[0]
[[1.000000e+00 1.057691e-21]]
1.0
1.057691e-21
 
 
17
[0]
[[1. 0.]]
1.0
0.0
 
 
18
[0]
[[1. 0.]]
1.0
0.0
 
 
19
[0]
[[1. 0.]]
1.0
0.0
 
 
20
[0]
[[1. 0.]]
1.0
0.0
 
 
21
[0]
[[1.0000000e+00 1.9134584e-19]]
1.0
1.9134584e-19
 
 
22
[0]
[[1. 0.]]
1.0
0.0
 
 
23
[0]
[[1. 0.]]
1.0
0.0
 
 
24
[0]
[[1. 0.]]
1.0
0.0
 
 
25
[0]
[[1. 0.]]
1

[0]
[[1.00000000e+00 1.10568476e-13]]
1.0
1.10568476e-13
 
 
199
[0]
[[9.9999976e-01 2.0861160e-07]]
0.99999976
2.086116e-07
 
 
200
[0]
[[1.000000e+00 7.353444e-11]]
1.0
7.353444e-11
 
 
201
[0]
[[1.0000e+00 9.1832e-32]]
1.0
9.1832e-32
 
 
202
[0]
[[1.0000000e+00 2.8992405e-16]]
1.0
2.8992405e-16
 
 
203
[0]
[[1.0000000e+00 1.3859285e-11]]
1.0
1.3859285e-11
 
 
204
[0]
[[1. 0.]]
1.0
0.0
 
 
205
[0]
[[1. 0.]]
1.0
0.0
 
 
206
[0]
[[1. 0.]]
1.0
0.0
 
 
207
[0]
[[1. 0.]]
1.0
0.0
 
 
208
[0]
[[1. 0.]]
1.0
0.0
 
 
209
[0]
[[1.000000e+00 2.123075e-36]]
1.0
2.123075e-36
 
 
210
[0]
[[1.000000e+00 6.125428e-11]]
1.0
6.125428e-11
 
 
211
[0]
[[1. 0.]]
1.0
0.0
 
 
212
[0]
[[1. 0.]]
1.0
0.0
 
 
213
[0]
[[1. 0.]]
1.0
0.0
 
 
214
[0]
[[1. 0.]]
1.0
0.0
 
 
215
[0]
[[1. 0.]]
1.0
0.0
 
 
216
[0]
[[1.0000000e+00 1.3312641e-15]]
1.0
1.3312641e-15
 
 
217
[0]
[[1.000000e+00 5.445689e-11]]
1.0
5.445689e-11
 
 
218
[0]
[[1. 0.]]
1.0
0.0
 
 
219
[0]
[[1. 0.]]
1.0
0.0
 
 
220
[0]
[[1. 0.]]
1.0
0.0
 
 
221
[0

[0]
[[1.0000000e+00 2.4808685e-35]]
1.0
2.4808685e-35
 
 
392
[0]
[[1. 0.]]
1.0
0.0
 
 
393
[0]
[[1. 0.]]
1.0
0.0
 
 
394
[0]
[[1.0000000e+00 1.1330984e-08]]
1.0
1.1330984e-08
 
 
395
[0]
[[0.9937256 0.0062744]]
0.9937256
0.0062743993
 
 
396
[0]
[[1. 0.]]
1.0
0.0
 
 
397
[0]
[[1. 0.]]
1.0
0.0
 
 
398
[0]
[[1.0000000e+00 2.8506074e-28]]
1.0
2.8506074e-28
 
 
399
[0]
[[1. 0.]]
1.0
0.0
 
 
400
[0]
[[1.0000000e+00 1.8816661e-35]]
1.0
1.8816661e-35
 
 
401
[0]
[[1.0000000e+00 3.9144838e-18]]
1.0
3.9144838e-18
 
 
402
[0]
[[9.9908614e-01 9.1380178e-04]]
0.99908614
0.0009138018
 
 
403
[0]
[[9.9999321e-01 6.8484105e-06]]
0.9999932
6.8484105e-06
 
 
404
[0]
[[1. 0.]]
1.0
0.0
 
 
405
[0]
[[1. 0.]]
1.0
0.0
 
 
406
[0]
[[1. 0.]]
1.0
0.0
 
 
407
[0]
[[1.000000e+00 4.517146e-09]]
1.0
4.517146e-09
 
 
408
[0]
[[1. 0.]]
1.0
0.0
 
 
409
[0]
[[1.0000000e+00 9.1106235e-17]]
1.0
9.1106235e-17
 
 
410
[0]
[[1.000000e+00 4.379217e-33]]
1.0
4.379217e-33
 
 
411
[0]
[[1. 0.]]
1.0
0.0
 
 
412
[0]
[[1. 0.]]
1

[0]
[[1. 0.]]
1.0
0.0
 
 
588
[0]
[[1. 0.]]
1.0
0.0
 
 
589
[0]
[[1.0000000e+00 7.0685705e-37]]
1.0
7.0685705e-37
 
 
590
[0]
[[1. 0.]]
1.0
0.0
 
 
591
[0]
[[1. 0.]]
1.0
0.0
 
 
592
[0]
[[1.0000000e+00 2.2395795e-18]]
1.0
2.2395795e-18
 
 
593
[0]
[[1. 0.]]
1.0
0.0
 
 
594
[0]
[[1. 0.]]
1.0
0.0
 
 
595
[0]
[[1.0000000e+00 1.3258248e-32]]
1.0
1.3258248e-32
 
 
596
[0]
[[1.000000e+00 8.155803e-27]]
1.0
8.155803e-27
 
 
597
[0]
[[1. 0.]]
1.0
0.0
 
 
598
[0]
[[1. 0.]]
1.0
0.0
 
 
599
[0]
[[9.9995172e-01 4.8322967e-05]]
0.9999517
4.8322967e-05
 
 
600
[0]
[[1.0000000e+00 1.5782019e-10]]
1.0
1.5782019e-10
 
 
601
[0]
[[1. 0.]]
1.0
0.0
 
 
602
[0]
[[1. 0.]]
1.0
0.0
 
 
603
[0]
[[1. 0.]]
1.0
0.0
 
 
604
[0]
[[1. 0.]]
1.0
0.0
 
 
605
[0]
[[1. 0.]]
1.0
0.0
 
 
606
[0]
[[1. 0.]]
1.0
0.0
 
 
607
[0]
[[0.99799985 0.00200008]]
0.99799985
0.002000082
 
 
608
[0]
[[1.0000000e+00 1.8263293e-34]]
1.0
1.8263293e-34
 
 
609
[0]
[[1. 0.]]
1.0
0.0
 
 
610
[0]
[[1. 0.]]
1.0
0.0
 
 
611
[0]
[[9.9998617e-01 1.

[0]
[[1. 0.]]
1.0
0.0
 
 
776
[0]
[[1. 0.]]
1.0
0.0
 
 
777
[0]
[[1. 0.]]
1.0
0.0
 
 
778
[0]
[[1. 0.]]
1.0
0.0
 
 
779
[0]
[[1.0000000e+00 4.2269075e-31]]
1.0
4.2269075e-31
 
 
780
[0]
[[1.0000000e+00 1.5148886e-12]]
1.0
1.5148886e-12
 
 
781
[0]
[[1.0000000e+00 3.0815064e-32]]
1.0
3.0815064e-32
 
 
782
[0]
[[1. 0.]]
1.0
0.0
 
 
783
[0]
[[1.000000e+00 2.794375e-12]]
1.0
2.794375e-12
 
 
784
[0]
[[1. 0.]]
1.0
0.0
 
 
785
[0]
[[1.0000000e+00 5.8937295e-35]]
1.0
5.8937295e-35
 
 
786
[0]
[[1. 0.]]
1.0
0.0
 
 
787
[0]
[[1.0000000e+00 1.3486863e-27]]
1.0
1.3486863e-27
 
 
788
[0]
[[1.0000000e+00 2.3223016e-32]]
1.0
2.3223016e-32
 
 
789
[0]
[[1. 0.]]
1.0
0.0
 
 
790
[0]
[[1. 0.]]
1.0
0.0
 
 
791
[0]
[[1.0000000e+00 1.1234285e-25]]
1.0
1.1234285e-25
 
 
792
[0]
[[1.0000000e+00 1.0437004e-11]]
1.0
1.0437004e-11
 
 
793
[0]
[[1.0000000e+00 3.7802057e-08]]
1.0
3.7802057e-08
 
 
794
[0]
[[1. 0.]]
1.0
0.0
 
 
795
[0]
[[1. 0.]]
1.0
0.0
 
 
796
[0]
[[1. 0.]]
1.0
0.0
 
 
797
[0]
[[9.999877e-01 1.23

[0]
[[1. 0.]]
1.0
0.0
 
 
965
[0]
[[1.0000000e+00 4.0237487e-11]]
1.0
4.0237487e-11
 
 
966
[0]
[[1. 0.]]
1.0
0.0
 
 
967
[0]
[[1.0000000e+00 1.6750673e-16]]
1.0
1.6750673e-16
 
 
968
[0]
[[1.0000000e+00 9.8711794e-30]]
1.0
9.8711794e-30
 
 
969
[0]
[[1. 0.]]
1.0
0.0
 
 
970
[0]
[[1.0000000e+00 1.6444415e-10]]
1.0
1.6444415e-10
 
 
971
[1]
[[0.29875323 0.70124674]]
0.29875323
0.70124674
 
 
972
[0]
[[1. 0.]]
1.0
0.0
 
 
973
[0]
[[9.9992073e-01 7.9219506e-05]]
0.9999207
7.9219506e-05
 
 
974
[0]
[[1. 0.]]
1.0
0.0
 
 
975
[0]
[[1. 0.]]
1.0
0.0
 
 
976
[0]
[[1.000000e+00 9.642514e-30]]
1.0
9.642514e-30
 
 
977
[0]
[[1. 0.]]
1.0
0.0
 
 
978
[0]
[[1. 0.]]
1.0
0.0
 
 
979
[0]
[[1.0000000e+00 1.7535452e-19]]
1.0
1.7535452e-19
 
 
980
[0]
[[1. 0.]]
1.0
0.0
 
 
981
[0]
[[1. 0.]]
1.0
0.0
 
 
982
[0]
[[1. 0.]]
1.0
0.0
 
 
983
[1]
[[0.33158714 0.66841286]]
0.33158714
0.66841286
 
 
984
[0]
[[1. 0.]]
1.0
0.0
 
 
985
[0]
[[1. 0.]]
1.0
0.0
 
 
986
[0]
[[1. 0.]]
1.0
0.0
 
 
987
[0]
[[1.0000000e+00 4.7

In [5]:
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)
print("positiv in percent: ", format((positiv / (positiv + negativ) * 100), '.2f'),'%')
print("negativ in percent: ", format((negativ / (positiv + negativ) * 100), '.2f'),'%')


print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)



#class_indices
#{'Dog': 1, 'Cat': 0}

 
 
positiv:  977
negativ:  23
positiv in percent:  97.70 %
negativ in percent:  2.30 %
 
 
result[0,0]:  977
result[0,1]:  23
 
 
result[0,0] > result[0,1]:  977
result[0,1]  > result[0,0]:  23


In [6]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

batch_size_Tatal_sample_size = 2000 


base_dir = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages' 
#base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate(x=valida_x, y=valida_y)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 4s 2ms/step
loss 0.1745023807654063
acc 0.978
acc: 97.80%


In [7]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

validation_steps = 2000   # 0 till 2000

batch_size_Tatal_sample_size = 20 

base_dir = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages' 
## base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


#valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate_generator(validation_generator, steps=validation_steps, verbose=1)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 66s 33ms/step
loss 0.17450167422905713
acc 0.9779999953210354
acc: 97.80%


In [8]:
validation_data_dir_normal = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation/Dog'

### validation_data_dir_normal = 'I:\\1_ssd_m.2\\PetImages\\validation\\Dog'



######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtensionNormal =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir_normal):                                        
    FilesAndExtensionNormal.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtensionNormal)

[('472', '.jpg'), ('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('104', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('122', '.jpg'), ('123', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.jpg'), ('138', '.

In [9]:
#next_validation_dir_dog= '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation_wrong_classicfide/dogs'
#next_validation_dir_dog= 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\dogs'

dogs_position00 = 0 
dogs_position01 = 0



for x in range(len(FilesAndExtensionNormal)):
    print(x)

    img_path = validation_data_dir_normal + '/' + FilesAndExtensionNormal[x][0] + FilesAndExtensionNormal[x][1]
    
    #img_path = validation_data_dir_normal + '\\' + FilesAndExtensionNormal[x][0] + FilesAndExtensionNormal[x][1]
    
    img_d = image.load_img(img_path, target_size=(150, 150))
    
    
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1_d = image.img_to_array(img_d)
    
        
    #normalization of the image to 0 ... 1
    x1_d_0_1 = x1_d / 255.0
    

    # We add a dimension to transform our array into a "batch"
    # of size (1, 224, 224, 3)
    x2_d = np.expand_dims(x1_d_0_1, axis=0)
    
    # Finally we preprocess the batch
    # (this does channel-wise color normalization)
    #x3_d = preprocess_input(x2_d)

    result = model.predict(x2_d)
    #result = model.predict(x3_d)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
    

    if result[0,0] > result[0,1]: 
        
        dogs_position00  = dogs_position00  + 1
        
    if result[0,1]  > result[0,0]:
        
        dogs_position01  = dogs_position01  + 1





print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

#class_indices
#{'Dog': 1, 'Cat': 0}   

0
[1]
[[5.8705716e-09 1.0000000e+00]]
5.8705716e-09
1.0
 
 
1
[1]
[[0. 1.]]
0.0
1.0
 
 
2
[1]
[[0.00934781 0.9906522 ]]
0.009347814
0.9906522
 
 
3
[1]
[[0.00147275 0.99852717]]
0.0014727517
0.99852717
 
 
4
[1]
[[2.9658615e-19 1.0000000e+00]]
2.9658615e-19
1.0
 
 
5
[1]
[[9.109321e-28 1.000000e+00]]
9.109321e-28
1.0
 
 
6
[1]
[[3.928096e-18 1.000000e+00]]
3.928096e-18
1.0
 
 
7
[1]
[[0. 1.]]
0.0
1.0
 
 
8
[1]
[[1.7162226e-17 1.0000000e+00]]
1.7162226e-17
1.0
 
 
9
[1]
[[4.3996564e-13 1.0000000e+00]]
4.3996564e-13
1.0
 
 
10
[1]
[[2.4347008e-30 1.0000000e+00]]
2.4347008e-30
1.0
 
 
11
[1]
[[9.233971e-22 1.000000e+00]]
9.233971e-22
1.0
 
 
12
[1]
[[3.3194802e-26 1.0000000e+00]]
3.3194802e-26
1.0
 
 
13
[1]
[[0. 1.]]
0.0
1.0
 
 
14
[1]
[[0. 1.]]
0.0
1.0
 
 
15
[1]
[[2.7459294e-24 1.0000000e+00]]
2.7459294e-24
1.0
 
 
16
[1]
[[2.0503952e-08 1.0000000e+00]]
2.0503952e-08
1.0
 
 
17
[1]
[[2.4657375e-33 1.0000000e+00]]
2.4657375e-33
1.0
 
 
18
[1]
[[0. 1.]]
0.0
1.0
 
 
19
[1]
[[3.350186e-13 

[1]
[[0. 1.]]
0.0
1.0
 
 
170
[1]
[[0. 1.]]
0.0
1.0
 
 
171
[1]
[[1.0354328e-17 1.0000000e+00]]
1.0354328e-17
1.0
 
 
172
[1]
[[0. 1.]]
0.0
1.0
 
 
173
[1]
[[0. 1.]]
0.0
1.0
 
 
174
[1]
[[2.8076935e-16 1.0000000e+00]]
2.8076935e-16
1.0
 
 
175
[1]
[[5.499052e-09 1.000000e+00]]
5.499052e-09
1.0
 
 
176
[1]
[[1.1634112e-10 1.0000000e+00]]
1.1634112e-10
1.0
 
 
177
[1]
[[1.2845167e-13 1.0000000e+00]]
1.2845167e-13
1.0
 
 
178
[1]
[[0. 1.]]
0.0
1.0
 
 
179
[1]
[[0. 1.]]
0.0
1.0
 
 
180
[1]
[[0. 1.]]
0.0
1.0
 
 
181
[1]
[[0. 1.]]
0.0
1.0
 
 
182
[1]
[[0. 1.]]
0.0
1.0
 
 
183
[1]
[[2.4682987e-17 1.0000000e+00]]
2.4682987e-17
1.0
 
 
184
[1]
[[1.6796586e-27 1.0000000e+00]]
1.6796586e-27
1.0
 
 
185
[1]
[[0. 1.]]
0.0
1.0
 
 
186
[1]
[[0. 1.]]
0.0
1.0
 
 
187
[1]
[[2.525892e-29 1.000000e+00]]
2.525892e-29
1.0
 
 
188
[1]
[[1.7721042e-20 1.0000000e+00]]
1.7721042e-20
1.0
 
 
189
[1]
[[0. 1.]]
0.0
1.0
 
 
190
[1]
[[2.9620747e-26 1.0000000e+00]]
2.9620747e-26
1.0
 
 
191
[1]
[[3.43116e-38 1.00000e

[1]
[[3.807588e-34 1.000000e+00]]
3.807588e-34
1.0
 
 
332
[1]
[[0. 1.]]
0.0
1.0
 
 
333
[1]
[[5.9178433e-17 1.0000000e+00]]
5.9178433e-17
1.0
 
 
334
[1]
[[0.14490074 0.8550993 ]]
0.14490074
0.8550993
 
 
335
[1]
[[3.1590682e-28 1.0000000e+00]]
3.1590682e-28
1.0
 
 
336
[1]
[[4.6346096e-34 1.0000000e+00]]
4.6346096e-34
1.0
 
 
337
[1]
[[0. 1.]]
0.0
1.0
 
 
338
[1]
[[3.6619444e-12 1.0000000e+00]]
3.6619444e-12
1.0
 
 
339
[1]
[[3.071892e-26 1.000000e+00]]
3.071892e-26
1.0
 
 
340
[1]
[[1.0783597e-08 1.0000000e+00]]
1.0783597e-08
1.0
 
 
341
[0]
[[0.9987174  0.00128257]]
0.9987174
0.0012825673
 
 
342
[1]
[[0. 1.]]
0.0
1.0
 
 
343
[1]
[[0. 1.]]
0.0
1.0
 
 
344
[1]
[[0. 1.]]
0.0
1.0
 
 
345
[1]
[[0. 1.]]
0.0
1.0
 
 
346
[1]
[[3.1375126e-27 1.0000000e+00]]
3.1375126e-27
1.0
 
 
347
[1]
[[2.29977e-12 1.00000e+00]]
2.29977e-12
1.0
 
 
348
[1]
[[1.860684e-24 1.000000e+00]]
1.860684e-24
1.0
 
 
349
[1]
[[2.4304846e-25 1.0000000e+00]]
2.4304846e-25
1.0
 
 
350
[1]
[[0. 1.]]
0.0
1.0
 
 
351
[1]

[1]
[[8.628890e-06 9.999914e-01]]
8.62889e-06
0.9999914
 
 
498
[1]
[[0. 1.]]
0.0
1.0
 
 
499
[1]
[[7.2951206e-22 1.0000000e+00]]
7.2951206e-22
1.0
 
 
500
[1]
[[1.2897362e-20 1.0000000e+00]]
1.2897362e-20
1.0
 
 
501
[1]
[[0. 1.]]
0.0
1.0
 
 
502
[1]
[[0.01697016 0.9830298 ]]
0.016970163
0.9830298
 
 
503
[1]
[[0.00600449 0.9939955 ]]
0.0060044914
0.9939955
 
 
504
[1]
[[0. 1.]]
0.0
1.0
 
 
505
[1]
[[0. 1.]]
0.0
1.0
 
 
506
[1]
[[0. 1.]]
0.0
1.0
 
 
507
[1]
[[6.520953e-27 1.000000e+00]]
6.520953e-27
1.0
 
 
508
[1]
[[4.598129e-16 1.000000e+00]]
4.598129e-16
1.0
 
 
509
[1]
[[2.9027817e-31 1.0000000e+00]]
2.9027817e-31
1.0
 
 
510
[1]
[[5.723313e-17 1.000000e+00]]
5.723313e-17
1.0
 
 
511
[1]
[[0. 1.]]
0.0
1.0
 
 
512
[1]
[[0. 1.]]
0.0
1.0
 
 
513
[1]
[[0. 1.]]
0.0
1.0
 
 
514
[1]
[[5.256515e-10 1.000000e+00]]
5.256515e-10
1.0
 
 
515
[1]
[[2.2579977e-25 1.0000000e+00]]
2.2579977e-25
1.0
 
 
516
[1]
[[0. 1.]]
0.0
1.0
 
 
517
[0]
[[0.99887365 0.00112639]]
0.99887365
0.0011263895
 
 
518

[1]
[[3.6613014e-27 1.0000000e+00]]
3.6613014e-27
1.0
 
 
664
[1]
[[1.4568479e-28 1.0000000e+00]]
1.4568479e-28
1.0
 
 
665
[1]
[[1.4060502e-33 1.0000000e+00]]
1.4060502e-33
1.0
 
 
666
[1]
[[0. 1.]]
0.0
1.0
 
 
667
[1]
[[0. 1.]]
0.0
1.0
 
 
668
[1]
[[2.0076538e-25 1.0000000e+00]]
2.0076538e-25
1.0
 
 
669
[1]
[[2.3361643e-08 1.0000000e+00]]
2.3361643e-08
1.0
 
 
670
[1]
[[0. 1.]]
0.0
1.0
 
 
671
[1]
[[7.0952336e-22 1.0000000e+00]]
7.0952336e-22
1.0
 
 
672
[1]
[[4.1524612e-17 1.0000000e+00]]
4.1524612e-17
1.0
 
 
673
[1]
[[4.3546835e-16 1.0000000e+00]]
4.3546835e-16
1.0
 
 
674
[1]
[[0. 1.]]
0.0
1.0
 
 
675
[1]
[[0. 1.]]
0.0
1.0
 
 
676
[1]
[[0. 1.]]
0.0
1.0
 
 
677
[1]
[[5.1592214e-14 1.0000000e+00]]
5.1592214e-14
1.0
 
 
678
[1]
[[6.1366716e-13 1.0000000e+00]]
6.1366716e-13
1.0
 
 
679
[1]
[[2.6478365e-31 1.0000000e+00]]
2.6478365e-31
1.0
 
 
680
[1]
[[0. 1.]]
0.0
1.0
 
 
681
[1]
[[5.2138184e-25 1.0000000e+00]]
5.2138184e-25
1.0
 
 
682
[1]
[[2.0762527e-29 1.0000000e+00]]
2.0762527e

[1]
[[0. 1.]]
0.0
1.0
 
 
825
[1]
[[0. 1.]]
0.0
1.0
 
 
826
[1]
[[3.2467164e-05 9.9996758e-01]]
3.2467164e-05
0.9999676
 
 
827
[1]
[[0. 1.]]
0.0
1.0
 
 
828
[1]
[[4.7039526e-33 1.0000000e+00]]
4.7039526e-33
1.0
 
 
829
[1]
[[8.6912554e-11 1.0000000e+00]]
8.6912554e-11
1.0
 
 
830
[1]
[[2.6289012e-19 1.0000000e+00]]
2.6289012e-19
1.0
 
 
831
[1]
[[2.4637324e-20 1.0000000e+00]]
2.4637324e-20
1.0
 
 
832
[0]
[[0.994052   0.00594796]]
0.994052
0.0059479554
 
 
833
[1]
[[0. 1.]]
0.0
1.0
 
 
834
[1]
[[1.9040545e-23 1.0000000e+00]]
1.9040545e-23
1.0
 
 
835
[1]
[[2.741334e-32 1.000000e+00]]
2.741334e-32
1.0
 
 
836
[1]
[[0. 1.]]
0.0
1.0
 
 
837
[1]
[[0. 1.]]
0.0
1.0
 
 
838
[1]
[[1.7823795e-23 1.0000000e+00]]
1.7823795e-23
1.0
 
 
839
[1]
[[1.5989317e-26 1.0000000e+00]]
1.5989317e-26
1.0
 
 
840
[1]
[[4.9423274e-36 1.0000000e+00]]
4.9423274e-36
1.0
 
 
841
[1]
[[1.6321417e-26 1.0000000e+00]]
1.6321417e-26
1.0
 
 
842
[1]
[[6.1125445e-33 1.0000000e+00]]
6.1125445e-33
1.0
 
 
843
[1]
[[0. 1.]]

[1]
[[7.39884e-31 1.00000e+00]]
7.39884e-31
1.0
 
 
992
[1]
[[4.3268693e-14 1.0000000e+00]]
4.3268693e-14
1.0
 
 
993
[1]
[[6.5361547e-09 1.0000000e+00]]
6.5361547e-09
1.0
 
 
994
[1]
[[5.0288376e-22 1.0000000e+00]]
5.0288376e-22
1.0
 
 
995
[1]
[[0. 1.]]
0.0
1.0
 
 
996
[1]
[[0. 1.]]
0.0
1.0
 
 
997
[1]
[[0. 1.]]
0.0
1.0
 
 
998
[1]
[[2.1318165e-35 1.0000000e+00]]
2.1318165e-35
1.0
 
 
999
[1]
[[6.3004186e-19 1.0000000e+00]]
6.3004186e-19
1.0
 
 
 
 
result[0,0] > result[0,1]:  21
result[0,1]  > result[0,0]:  979


In [10]:
print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

print(" ")
print(" ") 

print("positiv in percent: ", format((dogs_position00  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')
print("negativ in percent: ", format((dogs_position01  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')



result[0,0] > result[0,1]:  21
result[0,1]  > result[0,0]:  979
 
 
positiv in percent:  2.10 %
negativ in percent:  97.90 %


In [13]:
print("total negativ in percent: ", format(((dogs_position00 + cats_position01) / 2000 * 100), '.2f'),'%')
print("total positiv in percent: ", format(((dogs_position01 + cats_position00) / 2000 * 100), '.2f'),'%')

total negativ in percent:  2.20 %
total positiv in percent:  97.80 %
