In [1]:
import os
import numpy as np

In [2]:
#validation_data_dir = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation/Cat'
validation_data_dir = 'I:\\1_ssd_m.2\\PetImages\\validation\\Cat'


######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtension =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir):                                        
    FilesAndExtension.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtension)

[('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('103', '.jpg'), ('104', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('121', '.jpg'), ('122', '.jpg'), ('123', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.

In [3]:
from keras.models import load_model

#path_best_model = '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/0.9780__146-0.17-0.9945_CatsVRDogs_4000_inceptionV3_softmaxP98.h5'

#path_best_model = 'F:\\petsTF20model_weights\\CATSvsDOGS_4000_2000_inceptionV3_softmax_model.save98_TF2.1win.h5'

#model = load_model(path_best_model)

#model.load_weights('F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5')




path_best_model = 'F:\\petsTF20model_weights\\0.9925__175-0.00-0.9960_CatsVRDogs_4000_inceptionV3_softmaxP98_TF2.1win.h5'

model = load_model(path_best_model)

Using TensorFlow backend.


In [4]:
import cv2
import shutil

from keras.preprocessing import image
from keras.applications.inception_v3 import preprocess_input, decode_predictions
#result = model.evaluate(x=valida_x, y=valida_y) 

#next_validation_dir = '/media/ssd/Windows7_1/TB_DB_448_predict_sortANDcopy_classify_loop/2/validation/tb'
#next_validation_dir = 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\cats'

positiv=0
negativ=0

position00=0
position01=0

cats_position00 = 0 
cats_position01 = 0

for x in range(len(FilesAndExtension)):
    print(x)

    #print(FilesAndExtension[0][0] + FilesAndExtension[0][1])
    img_path = validation_data_dir + '\\' + FilesAndExtension[x][0] + FilesAndExtension[x][1]
    
    img = image.load_img(img_path, target_size=(150, 150))
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1 = image.img_to_array(img)
    # of size (1, 224, 224, 3)
    x2 = np.expand_dims(x1, axis=0)
    
    x3 = preprocess_input(x2)
    
    result = model.predict(x3)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
     
    

    if Labels_result == 0:
        
        positiv=positiv + 1
        
    if Labels_result == 1:
        
        negativ = negativ + 1
        
        
        
    if result[0,0] >= 0.5:
        
        position00 = position00 + 1
        
    if result[0,1]  >= 0.5:
        
        position01 = position01 + 1

        
        
        
    if result[0,0] > result[0,1]: 
        
        cats_position00 = cats_position00 + 1
        
        
    if result[0,1]  > result[0,0]:
        
        cats_position01 = cats_position01 + 1

        
        
        
        
        
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)



print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)





#class_indices
#{'Dog': 1, 'Cat': 0}

0
[0]
[[1. 0.]]
1.0
0.0
 
 
1
[0]
[[1. 0.]]
1.0
0.0
 
 
2
[1]
[[0. 1.]]
0.0
1.0
 
 
3
[0]
[[1.000000e+00 2.241753e-12]]
1.0
2.241753e-12
 
 
4
[0]
[[1. 0.]]
1.0
0.0
 
 
5
[0]
[[1. 0.]]
1.0
0.0
 
 
6
[0]
[[1. 0.]]
1.0
0.0
 
 
7
[1]
[[0. 1.]]
0.0
1.0
 
 
8
[0]
[[1. 0.]]
1.0
0.0
 
 
9
[1]
[[4.658195e-05 9.999534e-01]]
4.658195e-05
0.9999534
 
 
10
[1]
[[0. 1.]]
0.0
1.0
 
 
11
[0]
[[1. 0.]]
1.0
0.0
 
 
12
[0]
[[1. 0.]]
1.0
0.0
 
 
13
[0]
[[1. 0.]]
1.0
0.0
 
 
14
[0]
[[1. 0.]]
1.0
0.0
 
 
15
[0]
[[1. 0.]]
1.0
0.0
 
 
16
[0]
[[1. 0.]]
1.0
0.0
 
 
17
[0]
[[1. 0.]]
1.0
0.0
 
 
18
[0]
[[1. 0.]]
1.0
0.0
 
 
19
[0]
[[1. 0.]]
1.0
0.0
 
 
20
[0]
[[1. 0.]]
1.0
0.0
 
 
21
[1]
[[0. 1.]]
0.0
1.0
 
 
22
[1]
[[0. 1.]]
0.0
1.0
 
 
23
[0]
[[1.0000000e+00 5.9787196e-18]]
1.0
5.9787196e-18
 
 
24
[1]
[[0. 1.]]
0.0
1.0
 
 
25
[1]
[[0. 1.]]
0.0
1.0
 
 
26
[1]
[[0. 1.]]
0.0
1.0
 
 
27
[0]
[[1.0000000e+00 1.0808256e-36]]
1.0
1.0808256e-36
 
 
28
[1]
[[0. 1.]]
0.0
1.0
 
 
29
[0]
[[1. 0.]]
1.0
0.0
 
 
30
[0]
[[1.0

[0]
[[9.9997127e-01 2.8771608e-05]]
0.9999713
2.8771608e-05
 
 
231
[0]
[[1.0000000e+00 4.1486495e-30]]
1.0
4.1486495e-30
 
 
232
[0]
[[1. 0.]]
1.0
0.0
 
 
233
[0]
[[1. 0.]]
1.0
0.0
 
 
234
[0]
[[1. 0.]]
1.0
0.0
 
 
235
[0]
[[1. 0.]]
1.0
0.0
 
 
236
[0]
[[1. 0.]]
1.0
0.0
 
 
237
[0]
[[1. 0.]]
1.0
0.0
 
 
238
[0]
[[1. 0.]]
1.0
0.0
 
 
239
[0]
[[1. 0.]]
1.0
0.0
 
 
240
[0]
[[1.0000000e+00 6.4109116e-23]]
1.0
6.4109116e-23
 
 
241
[1]
[[0. 1.]]
0.0
1.0
 
 
242
[0]
[[1. 0.]]
1.0
0.0
 
 
243
[0]
[[1. 0.]]
1.0
0.0
 
 
244
[0]
[[1. 0.]]
1.0
0.0
 
 
245
[1]
[[6.670864e-18 1.000000e+00]]
6.670864e-18
1.0
 
 
246
[0]
[[1.0000000e+00 1.4054555e-17]]
1.0
1.4054555e-17
 
 
247
[0]
[[1. 0.]]
1.0
0.0
 
 
248
[0]
[[1. 0.]]
1.0
0.0
 
 
249
[0]
[[1. 0.]]
1.0
0.0
 
 
250
[1]
[[0. 1.]]
0.0
1.0
 
 
251
[0]
[[1. 0.]]
1.0
0.0
 
 
252
[0]
[[1. 0.]]
1.0
0.0
 
 
253
[0]
[[1.0000000e+00 7.6748035e-19]]
1.0
7.6748035e-19
 
 
254
[1]
[[7.915784e-12 1.000000e+00]]
7.915784e-12
1.0
 
 
255
[1]
[[0. 1.]]
0.0
1.0
 
 


[0]
[[1. 0.]]
1.0
0.0
 
 
462
[0]
[[1. 0.]]
1.0
0.0
 
 
463
[0]
[[1. 0.]]
1.0
0.0
 
 
464
[0]
[[1. 0.]]
1.0
0.0
 
 
465
[0]
[[1. 0.]]
1.0
0.0
 
 
466
[0]
[[1. 0.]]
1.0
0.0
 
 
467
[1]
[[0. 1.]]
0.0
1.0
 
 
468
[0]
[[1. 0.]]
1.0
0.0
 
 
469
[0]
[[1. 0.]]
1.0
0.0
 
 
470
[0]
[[1. 0.]]
1.0
0.0
 
 
471
[1]
[[0. 1.]]
0.0
1.0
 
 
472
[0]
[[1. 0.]]
1.0
0.0
 
 
473
[0]
[[1. 0.]]
1.0
0.0
 
 
474
[1]
[[0. 1.]]
0.0
1.0
 
 
475
[0]
[[1. 0.]]
1.0
0.0
 
 
476
[0]
[[1. 0.]]
1.0
0.0
 
 
477
[0]
[[1.0000000e+00 1.1047213e-32]]
1.0
1.1047213e-32
 
 
478
[0]
[[1. 0.]]
1.0
0.0
 
 
479
[1]
[[3.7512644e-17 1.0000000e+00]]
3.7512644e-17
1.0
 
 
480
[0]
[[1. 0.]]
1.0
0.0
 
 
481
[1]
[[0. 1.]]
0.0
1.0
 
 
482
[0]
[[1. 0.]]
1.0
0.0
 
 
483
[1]
[[0. 1.]]
0.0
1.0
 
 
484
[1]
[[0. 1.]]
0.0
1.0
 
 
485
[0]
[[1. 0.]]
1.0
0.0
 
 
486
[0]
[[1. 0.]]
1.0
0.0
 
 
487
[1]
[[0. 1.]]
0.0
1.0
 
 
488
[0]
[[1. 0.]]
1.0
0.0
 
 
489
[0]
[[1. 0.]]
1.0
0.0
 
 
490
[0]
[[1. 0.]]
1.0
0.0
 
 
491
[0]
[[1. 0.]]
1.0
0.0
 
 
492
[0]
[[

[[1. 0.]]
1.0
0.0
 
 
701
[0]
[[1. 0.]]
1.0
0.0
 
 
702
[0]
[[1. 0.]]
1.0
0.0
 
 
703
[1]
[[0. 1.]]
0.0
1.0
 
 
704
[1]
[[0. 1.]]
0.0
1.0
 
 
705
[0]
[[1. 0.]]
1.0
0.0
 
 
706
[0]
[[1. 0.]]
1.0
0.0
 
 
707
[0]
[[1. 0.]]
1.0
0.0
 
 
708
[0]
[[1. 0.]]
1.0
0.0
 
 
709
[0]
[[1. 0.]]
1.0
0.0
 
 
710
[0]
[[1. 0.]]
1.0
0.0
 
 
711
[1]
[[0. 1.]]
0.0
1.0
 
 
712
[0]
[[1. 0.]]
1.0
0.0
 
 
713
[0]
[[1. 0.]]
1.0
0.0
 
 
714
[0]
[[1. 0.]]
1.0
0.0
 
 
715
[0]
[[1. 0.]]
1.0
0.0
 
 
716
[0]
[[1. 0.]]
1.0
0.0
 
 
717
[0]
[[1. 0.]]
1.0
0.0
 
 
718
[0]
[[1. 0.]]
1.0
0.0
 
 
719
[0]
[[1. 0.]]
1.0
0.0
 
 
720
[1]
[[0. 1.]]
0.0
1.0
 
 
721
[0]
[[1. 0.]]
1.0
0.0
 
 
722
[0]
[[1. 0.]]
1.0
0.0
 
 
723
[0]
[[1. 0.]]
1.0
0.0
 
 
724
[1]
[[0. 1.]]
0.0
1.0
 
 
725
[0]
[[1. 0.]]
1.0
0.0
 
 
726
[1]
[[0.08184338 0.9181567 ]]
0.08184338
0.9181567
 
 
727
[0]
[[1. 0.]]
1.0
0.0
 
 
728
[0]
[[1. 0.]]
1.0
0.0
 
 
729
[0]
[[1. 0.]]
1.0
0.0
 
 
730
[1]
[[0. 1.]]
0.0
1.0
 
 
731
[0]
[[1. 0.]]
1.0
0.0
 
 
732
[0]
[[1. 0.]]
1

[0]
[[1. 0.]]
1.0
0.0
 
 
942
[0]
[[1. 0.]]
1.0
0.0
 
 
943
[1]
[[0. 1.]]
0.0
1.0
 
 
944
[0]
[[1.0000000e+00 3.3708045e-10]]
1.0
3.3708045e-10
 
 
945
[1]
[[0. 1.]]
0.0
1.0
 
 
946
[1]
[[0. 1.]]
0.0
1.0
 
 
947
[0]
[[1. 0.]]
1.0
0.0
 
 
948
[1]
[[1.9358816e-18 1.0000000e+00]]
1.9358816e-18
1.0
 
 
949
[0]
[[1. 0.]]
1.0
0.0
 
 
950
[1]
[[0. 1.]]
0.0
1.0
 
 
951
[0]
[[1. 0.]]
1.0
0.0
 
 
952
[0]
[[1. 0.]]
1.0
0.0
 
 
953
[0]
[[1. 0.]]
1.0
0.0
 
 
954
[0]
[[1. 0.]]
1.0
0.0
 
 
955
[1]
[[0. 1.]]
0.0
1.0
 
 
956
[0]
[[1.0000000e+00 1.9416297e-24]]
1.0
1.9416297e-24
 
 
957
[0]
[[1. 0.]]
1.0
0.0
 
 
958
[0]
[[1. 0.]]
1.0
0.0
 
 
959
[0]
[[1. 0.]]
1.0
0.0
 
 
960
[1]
[[0. 1.]]
0.0
1.0
 
 
961
[1]
[[0. 1.]]
0.0
1.0
 
 
962
[0]
[[1.0000000e+00 1.8277985e-28]]
1.0
1.8277985e-28
 
 
963
[0]
[[1. 0.]]
1.0
0.0
 
 
964
[0]
[[1.0000000e+00 1.4376077e-29]]
1.0
1.4376077e-29
 
 
965
[0]
[[1. 0.]]
1.0
0.0
 
 
966
[0]
[[1. 0.]]
1.0
0.0
 
 
967
[1]
[[0. 1.]]
0.0
1.0
 
 
968
[0]
[[1.000000e+00 6.358443e-2

In [5]:
print(" ")
print(" ")        

print("positiv: ", positiv)
print("negativ: ", negativ)
print("positiv in percent: ", format((positiv / (positiv + negativ) * 100), '.2f'),'%')
print("negativ in percent: ", format((negativ / (positiv + negativ) * 100), '.2f'),'%')


print(" ")
print(" ")        

print("result[0,0]: ", position00)
print("result[0,1]: ", position01)



print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", cats_position00)
print("result[0,1]  > result[0,0]: ", cats_position01)



#class_indices
#{'Dog': 1, 'Cat': 0}

 
 
positiv:  702
negativ:  298
positiv in percent:  70.20 %
negativ in percent:  29.80 %
 
 
result[0,0]:  702
result[0,1]:  298
 
 
result[0,0] > result[0,1]:  702
result[0,1]  > result[0,0]:  298


In [6]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

batch_size_Tatal_sample_size = 2000 

base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate(x=valida_x, y=valida_y)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 7s 4ms/step
loss 0.35562051463638844
acc 0.9775000214576721
acc: 97.75%


In [7]:
import os
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


img_rows, img_cols = 150, 150
img_channels = 3

validation_steps = 2000   # 0 till 2000

batch_size_Tatal_sample_size = 20 

base_dir = 'I:\\1_ssd_m.2\\PetImages' 

validation_dir = os.path.join(base_dir, 'validation')
print("Finished dir read")

validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        validation_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size_Tatal_sample_size,
        class_mode='categorical')


#valida_x, valida_y = validation_generator.next()
#validation_x, validation_y = validation_generator.next()

result = model.evaluate_generator(validation_generator, steps=validation_steps, verbose=1)

for name, value in zip(model.metrics_names, result):
    print(name, value)
   
print("{0}: {1:.2%}".format(model.metrics_names[1], result[1]))

Finished dir read
Found 2000 images belonging to 2 classes.
2000/2000 [==============================] - 94s 47ms/step
loss 1.5107557773590088
acc 0.9775000214576721
acc: 97.75%


In [8]:
validation_data_dir_normal = 'I:\\1_ssd_m.2\\PetImages\\validation\\Dog'



######################  full Root, Dirnames, Filenames, file extension
######################  Root, Dirnames, Filenames, file extension
FilesAndExtensionNormal =[]

for Root, Dirnames, Filenames1 in os.walk(validation_data_dir_normal):                                        
    FilesAndExtensionNormal.extend(os.path.splitext(name) for name in Filenames1)  
    
     
print(FilesAndExtensionNormal)

[('100', '.jpg'), ('1000', '.jpg'), ('1001', '.jpg'), ('1002', '.jpg'), ('1003', '.jpg'), ('1004', '.jpg'), ('1005', '.jpg'), ('1006', '.jpg'), ('1007', '.jpg'), ('1008', '.jpg'), ('1009', '.jpg'), ('101', '.jpg'), ('1010', '.jpg'), ('1011', '.jpg'), ('1012', '.jpg'), ('1013', '.jpg'), ('1014', '.jpg'), ('1015', '.jpg'), ('1016', '.jpg'), ('1017', '.jpg'), ('1018', '.jpg'), ('1019', '.jpg'), ('102', '.jpg'), ('103', '.jpg'), ('104', '.jpg'), ('105', '.jpg'), ('106', '.jpg'), ('107', '.jpg'), ('108', '.jpg'), ('109', '.jpg'), ('110', '.jpg'), ('111', '.jpg'), ('112', '.jpg'), ('113', '.jpg'), ('114', '.jpg'), ('115', '.jpg'), ('116', '.jpg'), ('117', '.jpg'), ('118', '.jpg'), ('119', '.jpg'), ('120', '.jpg'), ('121', '.jpg'), ('122', '.jpg'), ('123', '.jpg'), ('124', '.jpg'), ('125', '.jpg'), ('126', '.jpg'), ('127', '.jpg'), ('128', '.jpg'), ('129', '.jpg'), ('130', '.jpg'), ('131', '.jpg'), ('132', '.jpg'), ('133', '.jpg'), ('134', '.jpg'), ('135', '.jpg'), ('136', '.jpg'), ('137', '.

In [9]:
#next_validation_dir_dog= '/media/ssd/Windows7_1/1_ssd_m.2/PetImages/validation_wrong_classicfide/dogs'
next_validation_dir_dog= 'I:\\1_ssd_m.2\\PetImages\\validation_wrong_classicfide\\dogs'

dogs_position00 = 0 
dogs_position01 = 0


for x in range(len(FilesAndExtensionNormal)):
    print(x)

    #print(FilesAndExtension[0][0] + FilesAndExtension[0][1])


    img = cv2.imread(validation_data_dir_normal + '\\' + FilesAndExtensionNormal[x][0] + FilesAndExtensionNormal[x][1])
    # `x` is a float32 Numpy array of shape (224, 224, 3)
    x1 = image.img_to_array(img)

    # We add a dimension to transform our array into a "batch"
    # of size (1, 224, 224, 3)
    x2 = np.expand_dims(x1, axis=0)

    # Finally we preprocess the batch
    # (this does channel-wise color normalization)
    x3 = preprocess_input(x2)

    result = model.predict(x3)
    
    
    Labels_result = result.argmax(axis=-1) 
    print(Labels_result)
    
    print(result)
    print(result[0,0])
    print(result[0,1])
    print(" ")
    print(" ")
    

    if result[0,0] > result[0,1]: 
        
        dogs_position00  = dogs_position00  + 1
        
    if result[0,1]  > result[0,0]:
        
        dogs_position01  = dogs_position01  + 1





print(" ")
print(" ")        

print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

0
[0]
[[1.000000e+00 5.216833e-36]]
1.0
5.216833e-36
 
 
1
[0]
[[1. 0.]]
1.0
0.0
 
 
2
[0]
[[1.0000000e+00 2.0535331e-09]]
1.0
2.0535331e-09
 
 
3
[0]
[[9.9980444e-01 1.9554600e-04]]
0.99980444
0.000195546
 
 
4
[0]
[[1.0000000e+00 2.0729083e-26]]
1.0
2.0729083e-26
 
 
5
[0]
[[1. 0.]]
1.0
0.0
 
 
6
[0]
[[1.0000000e+00 5.3713476e-17]]
1.0
5.3713476e-17
 
 
7
[1]
[[0. 1.]]
0.0
1.0
 
 
8
[0]
[[1. 0.]]
1.0
0.0
 
 
9
[1]
[[5.2580626e-06 9.9999475e-01]]
5.2580626e-06
0.99999475
 
 
10
[0]
[[1. 0.]]
1.0
0.0
 
 
11
[1]
[[0. 1.]]
0.0
1.0
 
 
12
[1]
[[0. 1.]]
0.0
1.0
 
 
13
[1]
[[0. 1.]]
0.0
1.0
 
 
14
[1]
[[0. 1.]]
0.0
1.0
 
 
15
[1]
[[2.5735192e-30 1.0000000e+00]]
2.5735192e-30
1.0
 
 
16
[0]
[[1.000000e+00 1.915416e-26]]
1.0
1.915416e-26
 
 
17
[0]
[[1.0000000e+00 2.3045809e-32]]
1.0
2.3045809e-32
 
 
18
[0]
[[1.000000e+00 7.784196e-26]]
1.0
7.784196e-26
 
 
19
[0]
[[1. 0.]]
1.0
0.0
 
 
20
[0]
[[1.00000e+00 3.78711e-24]]
1.0
3.78711e-24
 
 
21
[0]
[[1. 0.]]
1.0
0.0
 
 
22
[1]
[[9.3251816e-04 

202
[1]
[[0. 1.]]
0.0
1.0
 
 
203
[0]
[[1. 0.]]
1.0
0.0
 
 
204
[0]
[[1. 0.]]
1.0
0.0
 
 
205
[0]
[[1.0000000e+00 9.9321515e-21]]
1.0
9.9321515e-21
 
 
206
[1]
[[1.789153e-28 1.000000e+00]]
1.789153e-28
1.0
 
 
207
[0]
[[1. 0.]]
1.0
0.0
 
 
208
[0]
[[1. 0.]]
1.0
0.0
 
 
209
[0]
[[1. 0.]]
1.0
0.0
 
 
210
[0]
[[1. 0.]]
1.0
0.0
 
 
211
[0]
[[1. 0.]]
1.0
0.0
 
 
212
[0]
[[1. 0.]]
1.0
0.0
 
 
213
[0]
[[9.9999356e-01 6.4212177e-06]]
0.99999356
6.4212177e-06
 
 
214
[0]
[[1. 0.]]
1.0
0.0
 
 
215
[0]
[[1.00000e+00 5.43377e-14]]
1.0
5.43377e-14
 
 
216
[0]
[[0.9322333  0.06776674]]
0.9322333
0.06776674
 
 
217
[1]
[[0. 1.]]
0.0
1.0
 
 
218
[0]
[[1. 0.]]
1.0
0.0
 
 
219
[1]
[[0. 1.]]
0.0
1.0
 
 
220
[0]
[[1. 0.]]
1.0
0.0
 
 
221
[0]
[[1. 0.]]
1.0
0.0
 
 
222
[1]
[[1.0232117e-13 1.0000000e+00]]
1.0232117e-13
1.0
 
 
223
[0]
[[1. 0.]]
1.0
0.0
 
 
224
[0]
[[1. 0.]]
1.0
0.0
 
 
225
[0]
[[1. 0.]]
1.0
0.0
 
 
226
[1]
[[0. 1.]]
0.0
1.0
 
 
227
[0]
[[1. 0.]]
1.0
0.0
 
 
228
[1]
[[4.347188e-28 1.000000e+

[0]
[[1. 0.]]
1.0
0.0
 
 
404
[0]
[[1. 0.]]
1.0
0.0
 
 
405
[0]
[[1. 0.]]
1.0
0.0
 
 
406
[0]
[[1. 0.]]
1.0
0.0
 
 
407
[1]
[[0.00176595 0.99823403]]
0.001765951
0.99823403
 
 
408
[0]
[[1.0000000e+00 3.7179423e-32]]
1.0
3.7179423e-32
 
 
409
[0]
[[1. 0.]]
1.0
0.0
 
 
410
[1]
[[0. 1.]]
0.0
1.0
 
 
411
[0]
[[1.000000e+00 6.408929e-16]]
1.0
6.408929e-16
 
 
412
[1]
[[1.4796814e-22 1.0000000e+00]]
1.4796814e-22
1.0
 
 
413
[0]
[[1. 0.]]
1.0
0.0
 
 
414
[1]
[[0. 1.]]
0.0
1.0
 
 
415
[0]
[[1. 0.]]
1.0
0.0
 
 
416
[0]
[[1. 0.]]
1.0
0.0
 
 
417
[0]
[[1. 0.]]
1.0
0.0
 
 
418
[0]
[[1.000000e+00 4.914831e-17]]
1.0
4.914831e-17
 
 
419
[1]
[[0. 1.]]
0.0
1.0
 
 
420
[0]
[[1.0000e+00 6.3416e-35]]
1.0
6.3416e-35
 
 
421
[0]
[[1.0000000e+00 1.4723696e-19]]
1.0
1.4723696e-19
 
 
422
[0]
[[1. 0.]]
1.0
0.0
 
 
423
[0]
[[1.0000000e+00 5.8336897e-21]]
1.0
5.8336897e-21
 
 
424
[1]
[[0. 1.]]
0.0
1.0
 
 
425
[0]
[[1. 0.]]
1.0
0.0
 
 
426
[0]
[[1.0000000e+00 6.8048635e-21]]
1.0
6.8048635e-21
 
 
427
[1]
[[0.

[0]
[[1. 0.]]
1.0
0.0
 
 
605
[0]
[[1. 0.]]
1.0
0.0
 
 
606
[1]
[[0. 1.]]
0.0
1.0
 
 
607
[0]
[[1.0000000e+00 5.6190878e-08]]
1.0
5.6190878e-08
 
 
608
[0]
[[1. 0.]]
1.0
0.0
 
 
609
[1]
[[0. 1.]]
0.0
1.0
 
 
610
[1]
[[0. 1.]]
0.0
1.0
 
 
611
[1]
[[0. 1.]]
0.0
1.0
 
 
612
[0]
[[1. 0.]]
1.0
0.0
 
 
613
[0]
[[1.000000e+00 4.992645e-33]]
1.0
4.992645e-33
 
 
614
[0]
[[0.9635943  0.03640568]]
0.9635943
0.036405675
 
 
615
[1]
[[0. 1.]]
0.0
1.0
 
 
616
[1]
[[0. 1.]]
0.0
1.0
 
 
617
[1]
[[0. 1.]]
0.0
1.0
 
 
618
[0]
[[1. 0.]]
1.0
0.0
 
 
619
[0]
[[1. 0.]]
1.0
0.0
 
 
620
[0]
[[1. 0.]]
1.0
0.0
 
 
621
[0]
[[1. 0.]]
1.0
0.0
 
 
622
[0]
[[1.0000000e+00 9.9159685e-17]]
1.0
9.9159685e-17
 
 
623
[1]
[[0. 1.]]
0.0
1.0
 
 
624
[1]
[[0. 1.]]
0.0
1.0
 
 
625
[0]
[[1.0000000e+00 3.4187613e-23]]
1.0
3.4187613e-23
 
 
626
[0]
[[9.999925e-01 7.462087e-06]]
0.9999925
7.462087e-06
 
 
627
[0]
[[1.000000e+00 1.329147e-13]]
1.0
1.329147e-13
 
 
628
[1]
[[0. 1.]]
0.0
1.0
 
 
629
[0]
[[1. 0.]]
1.0
0.0
 
 
630
[

[1]
[[0. 1.]]
0.0
1.0
 
 
815
[1]
[[0. 1.]]
0.0
1.0
 
 
816
[0]
[[1. 0.]]
1.0
0.0
 
 
817
[0]
[[1. 0.]]
1.0
0.0
 
 
818
[1]
[[0. 1.]]
0.0
1.0
 
 
819
[0]
[[1. 0.]]
1.0
0.0
 
 
820
[0]
[[1.0000000e+00 6.2869413e-29]]
1.0
6.2869413e-29
 
 
821
[1]
[[0. 1.]]
0.0
1.0
 
 
822
[1]
[[0. 1.]]
0.0
1.0
 
 
823
[0]
[[1. 0.]]
1.0
0.0
 
 
824
[0]
[[1. 0.]]
1.0
0.0
 
 
825
[1]
[[1.9013568e-28 1.0000000e+00]]
1.9013568e-28
1.0
 
 
826
[0]
[[1.0000000e+00 1.5734004e-08]]
1.0
1.5734004e-08
 
 
827
[1]
[[4.914359e-11 1.000000e+00]]
4.914359e-11
1.0
 
 
828
[0]
[[1. 0.]]
1.0
0.0
 
 
829
[0]
[[1. 0.]]
1.0
0.0
 
 
830
[0]
[[1.0000000e+00 1.0119907e-33]]
1.0
1.0119907e-33
 
 
831
[0]
[[1.0000000e+00 6.1887406e-10]]
1.0
6.1887406e-10
 
 
832
[1]
[[0. 1.]]
0.0
1.0
 
 
833
[1]
[[0. 1.]]
0.0
1.0
 
 
834
[1]
[[9.536096e-13 1.000000e+00]]
9.536096e-13
1.0
 
 
835
[0]
[[1. 0.]]
1.0
0.0
 
 
836
[1]
[[0. 1.]]
0.0
1.0
 
 
837
[0]
[[1. 0.]]
1.0
0.0
 
 
838
[0]
[[1.000000e+00 3.852628e-10]]
1.0
3.852628e-10
 
 
839
[0]

In [10]:
print("result[0,0] > result[0,1]: ", dogs_position00 )
print("result[0,1]  > result[0,0]: ", dogs_position01 )

print(" ")
print(" ") 

print("positiv in percent: ", format((dogs_position00  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')
print("negativ in percent: ", format((dogs_position01  / (dogs_position00  + dogs_position01 ) * 100), '.2f'),'%')



result[0,0] > result[0,1]:  695
result[0,1]  > result[0,0]:  305
 
 
positiv in percent:  69.50 %
negativ in percent:  30.50 %
